Add support for media:thumbnail as episode_art_url.
gpodder/podcastparser pull request #31
Opened 2021-07-17 02:29 UTC by auouymous

2021-07-18 08:33 UTC, thp commented on podcastparser.py
> +            handler.set_episode_attr(self.key, self.filter_func(value))
Maybe do it like this to share code:

```
class EpisodeAttrFromHref(Target):
    ATTRIBUTE = 'href'

    def start(self, handler, attrs):
        value = attrs.get(self.ATTRIBUTE)
        if value:
            value = urlparse.urljoin(handler.base, value)
             handler.set_episode_attr(self.key, self.filter_func(value))


class EpisodeAttrFromUrl(EpisodeAttrFromHref):
    ATTRIBUTE = 'url'
```

2021-07-18 08:34 UTC, thp requested changes
One comment to avoid code duplication. Rest looks good.

2021-07-18 11:10 UTC, auouymous commented on podcastparser.py
> +            handler.set_episode_attr(self.key, self.filter_func(value))
Good idea, done.

2021-07-18 11:32 UTC, elelay commented
Better with a test ;-)

2021-07-21 07:39 UTC, auouymous commented
Added some tests.

2021-07-21 17:55 UTC, merged

2021-07-21 17:55 UTC, elelay commented
Merged, thanks :-)