Add rss/channel/itunes:summary handling
gpodder/podcastparser pull request #49
Opened 2024-05-15 15:59 UTC by CJxD

We noticed that some podcasts don't have descriptions but do have itunes summaries.

Here's a file that can be used in a test: http://netstorage.discovery.com/ahc/podcasts/2016/ahc-ato-podcastrss.xml

2024-05-18 08:38 UTC, thp requested changes
From above that block:

```
# If you modify the mapping, don't forget to also update the documentation
# section "Supported XML Elements and Attributes" in doc/index.rst
```

Apart from that, it's good. It might cause some feeds that have both description and itunes:summary with different content to have different results after parsing, though.

2024-05-22 01:19 UTC, auouymous commented
@thp Could we add an `optional` or `secondary` flag to `set_podcast_attr()` so it only sets the value if None? Then description could be the primary field and summary a secondary, no matter which order they are found in the feed.

2024-06-25 14:39 UTC, CJxD commented
Just got back to this! Sorry for the delay. Yes I can look into a suitable fallback behaviour :)

2024-06-25 15:11 UTC, CJxD commented
Here's a question, the episode description behaviour is similar to what I have suggested here so I wonder if this change-if-none behaviour should also be applied in this case.

I also noted how HTML is handled in description but not in the summary according to this. Is it accurate? Should the same happen for channel/description?

```
**rss/channel/item/description**
    Episode description.
    If it contains html, it's returned as description_html.
    Otherwise it's returned as description (whitespace is squashed).
    See Mozilla's article `Why RSS Content Module is Popular`

**rss/channel/item/itunes:summary**
    Episode description (whitespace is squashed).
```

2024-07-23 05:20 UTC, auouymous commented
> Here's a question, the episode description behaviour is similar to what I have suggested here so I wonder if this change-if-none behaviour should also be applied in this case.

Yes. It would have the same issue, unless it already only changes if none.


> I also noted how HTML is handled in description but not in the summary according to this. Is it accurate? Should the same happen for channel/description?

It could if the RSS spec supports HTML in channel descriptions. gPodder only supports HTML descriptions for episodes and would need to detect an HTML channel description and strip it.

2025-09-26 14:18 UTC, thp commented
Bump; is there anything left to do here or can this be merged? :)

2025-10-17 12:18 UTC, thp requested changes
This is super clean now, just need to remove the version bump (it's done separately as part of releasing, not in code changes in branches). Thanks!

2025-10-20 10:24 UTC, CJxD commented on podcastparser.py
> +__version__ = '0.6.11'
Done :)

2025-10-20 20:42 UTC, merged

2025-10-20 20:42 UTC, thp commented
Merged, thanks!

2025-11-18 12:33 UTC, thp commented
> Hey @thp - will there be a new release soon? I'd like to update the library in my project :)

Done: https://github.com/gpodder/podcastparser/commit/5ac16fa16520303dc6739365924979bfb8a97758